# Generated by Django 4.2.7 on 2024-04-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('event_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Event Type ID')),
                ('event_name', models.CharField(max_length=80, verbose_name='Event Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='Event_Type_IOT_Type_Map',
            fields=[
                ('event_iot_map_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Event IOT Type Id')),
                ('event_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Event_Type_Id', to='masterdata.event_type', verbose_name='Event Type Id')),
                ('iot_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_IOT_Type', to='core.iot_type', verbose_name='IOT Type')),
            ],
            options={
                'verbose_name': 'Event/IOT Type',
                'verbose_name_plural': 'Event/IOT Types',
                'unique_together': {('event_type_id', 'iot_type_id')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Unit ID')),
                ('unit_name', models.CharField(max_length=80, unique=True, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('param_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Param ID')),
                ('param_name', models.CharField(max_length=80, unique=True, verbose_name='Param Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Param_Unit', to='masterdata.unit', verbose_name='Param Unit')),
            ],
            options={
                'verbose_name': 'Param',
                'verbose_name_plural': 'Params',
            },
        ),
        migrations.CreateModel(
            name='EventRuleParams',
            fields=[
                ('event_rule_param_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Event Rule Param Id')),
                ('event_type_iot_map_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Event_Type_IOT_Type_Map_Id', to='masterdata.event_type_iot_type_map', verbose_name='Event Type IOT Type Map Id')),
                ('paramid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Param_Id', to='masterdata.param', verbose_name='Param Id')),
            ],
            options={
                'verbose_name': 'Event Rule Param',
                'verbose_name_plural': 'Event Rule Params',
                'unique_together': {('event_type_iot_map_id', 'paramid')},
            },
        ),
    ]
