# Generated by Django 4.2.7 on 2024-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='param',
            options={'verbose_name': 'Monitoring Parameter', 'verbose_name_plural': 'Monitoring Parameters'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Monitoring Unit', 'verbose_name_plural': 'Monitoring Units'},
        ),
        migrations.AlterField(
            model_name='event_type',
            name='event_name',
            field=models.CharField(max_length=80, verbose_name='Event Type'),
        ),
    ]
