# Generated by Django 4.2.7 on 2024-04-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Rule',
            fields=[
                ('event_rule_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Event_RuleID')),
                ('name', models.CharField(max_length=80, null=True, unique=True, verbose_name='Rule Name')),
                ('rule_frequency', models.IntegerField(null=True, verbose_name='Frequency')),
                ('rule_frequency_unit', models.CharField(choices=[('sec', 'SECOND'), ('d', 'DAY'), ('m', 'MONTH'), ('y', 'YEAR')], max_length=40, null=True, verbose_name='Frequency Unit')),
            ],
            options={
                'verbose_name': 'Event Rule',
                'verbose_name_plural': 'Event Rules',
            },
        ),
        migrations.CreateModel(
            name='Event_Rule_Params',
            fields=[
                ('event_rule_param_ispec_condition_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Event Rule Parameter Id')),
                ('operator1', models.CharField(blank=True, choices=[('=', '='), ('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>=')], max_length=40, null=True, verbose_name='Operator-1')),
                ('value1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value1')),
                ('condition', models.CharField(blank=True, choices=[('and', 'AND'), ('or', 'OR')], max_length=40, null=True, verbose_name='Condition')),
                ('operator2', models.CharField(blank=True, choices=[('=', '='), ('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>=')], max_length=40, null=True, verbose_name='Operator-2')),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Value2')),
                ('value_text', models.CharField(blank=True, max_length=80, null=True, verbose_name='Condition(In Text)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration')),
                ('event_rule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventmanagement.event_rule', verbose_name='Event Rule Id')),
                ('param_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.param', verbose_name='Parameter ID')),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.unit', verbose_name='Duration Unit')),
            ],
            options={
                'verbose_name': 'Event Rule Parameter',
                'verbose_name_plural': 'Event Rule Parameters',
            },
        ),
    ]
