# Generated by Django 4.2.7 on 2024-04-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('eventmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_rule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='event_rule',
            name='event_iot_map_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.event_type_iot_type_map', verbose_name='Event_Type_IOT_Type_Map_Id'),
        ),
        migrations.AddField(
            model_name='event_rule',
            name='event_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.event_type', verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='event_rule',
            name='iot_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.iot_type', verbose_name='IOT Type'),
        ),
        migrations.AlterUniqueTogether(
            name='event_rule_params',
            unique_together={('event_rule_id', 'param_id')},
        ),
    ]
