# Generated by Django 4.2.7 on 2024-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_rule',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, help_text='In UTC', null=True, verbose_name='Created DateTime'),
        ),
    ]
