# Generated by Django 4.2.7 on 2024-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0002_event_rule_params_value_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_rule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='event_rule_params',
            name='value_text',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Condition(In Text)'),
        ),
    ]
