# Generated by Django 4.2.7 on 2024-05-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDetail',
            fields=[
                ('app_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='APP Id')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('base_url', models.CharField(max_length=300, verbose_name='Base URL')),
            ],
            options={
                'verbose_name': 'APP Detail',
                'verbose_name_plural': 'APP Detail',
            },
        ),
        migrations.CreateModel(
            name='APIDetail',
            fields=[
                ('api_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='API Id')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('end_point_url', models.CharField(max_length=300, verbose_name='End Point')),
                ('type', models.CharField(choices=[('inbound', 'EM API'), ('outbound', 'LIMS API'), ('connection', 'Create Connection')], max_length=40, verbose_name='Type')),
                ('success_code', models.IntegerField(blank=True, default=200, null=True, verbose_name='Success Code')),
                ('authorization_property_id', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Authorization Property Id')),
                ('authorization_keyword', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Authorization Keyword')),
                ('processing_script', models.TextField()),
                ('app_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidetails.applicationdetail', verbose_name='App Id')),
            ],
            options={
                'verbose_name': 'API Detail',
                'verbose_name_plural': 'API Detail',
            },
        ),
        migrations.CreateModel(
            name='API_Property_Details',
            fields=[
                ('api_property_details_id', models.AutoField(primary_key=True, serialize=False, verbose_name='API Property Details Id')),
                ('property_id', models.CharField(default='', max_length=80, verbose_name='Property Id')),
                ('property_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Property Value')),
                ('is_keyword', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=40, null=True, verbose_name='Is Keyword')),
                ('is_url_property', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=40, null=True, verbose_name='Is URL Property')),
                ('api_detail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apidetails.apidetail', verbose_name='API Detail Id')),
            ],
            options={
                'verbose_name': 'API Property Detail',
                'verbose_name_plural': 'API Property Detail',
                'unique_together': {('api_detail_id', 'property_id')},
            },
        ),
    ]
