# Generated by Django 4.2.7 on 2024-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidetails', '0002_apidetail_created_by_apidetail_created_dt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apidetail',
            options={'verbose_name': 'Processing Actions', 'verbose_name_plural': 'Processing Actions'},
        ),
        migrations.AlterModelOptions(
            name='applicationdetail',
            options={'verbose_name': 'Registered Applications', 'verbose_name_plural': 'Registered Applications'},
        ),
        migrations.AlterField(
            model_name='apidetail',
            name='processing_script',
            field=models.TextField(verbose_name='Processing Script'),
        ),
    ]
