# Generated by Django 4.2.7 on 2024-05-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Periodic Task',
                'verbose_name_plural': 'Periodic Tasks',
            },
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='TaskAudit',
            fields=[
                ('task_audit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Task Audit Id')),
                ('name', models.CharField(default='', help_text='Short Description For This Task', max_length=200, verbose_name='Task Id')),
                ('uuid', models.CharField(default='', max_length=200, verbose_name='IOT Device Id')),
                ('task_id', models.CharField(help_text='Thread ID for the Task that was run', max_length=255, verbose_name='Thread ID')),
                ('api_url', models.CharField(default='', help_text='EM API URL', max_length=400, verbose_name='EM API URL')),
                ('status', models.CharField(help_text='EM API Call Status', max_length=50, verbose_name='EM API Call Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='In UTC', verbose_name='Created DateTime')),
                ('response_text', models.JSONField()),
                ('data_consumed_by_api', models.IntegerField(blank=True, help_text='In Bytes', null=True, verbose_name='Data Consumed by EM API call')),
                ('condition_evaluation', models.JSONField(default='')),
                ('lims_connection_api_url', models.CharField(default='', help_text='LIMS Connection API URL', max_length=400, verbose_name='LIMS Connection API URL')),
                ('lims_connection_api_status', models.CharField(default='', help_text='LIMS Connection API Status', max_length=50, verbose_name='LIMS Connection API Status')),
                ('lims_connection_api_call_param', models.JSONField(default='', verbose_name='LIMS Connection API Call Param')),
                ('lims_connection_api_response_text', models.JSONField(default='', verbose_name='LIMS Connection API Call Response')),
                ('data_consumed_by_lims_connection_api', models.IntegerField(blank=True, help_text='In Bytes', null=True, verbose_name='Data Consumed by LIMS Connection API call')),
                ('lims_api_url', models.CharField(default='', help_text='LIMS API URL', max_length=400, verbose_name='LIMS API URL')),
                ('lims_status', models.CharField(default='', help_text='LIMS API Status', max_length=50, verbose_name='LIMS API Status')),
                ('lims_api_call_param', models.JSONField(default='', verbose_name='LIMS API Call Param')),
                ('lims_response_text', models.JSONField(default='', verbose_name='LIMS API Call Response')),
                ('data_consumed_by_lims_api', models.IntegerField(blank=True, help_text='In Bytes', null=True, verbose_name='Data Consumed by LIMS API call')),
                ('total_data_consumed', models.IntegerField(blank=True, help_text='In Bytes', null=True, verbose_name='Total Data Consumed')),
            ],
        ),
    ]
