# Generated by Django 4.2.7 on 2024-05-14 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventmanagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customperiodictask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customperiodictask',
            name='event_rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanagement.event_rule', verbose_name='Event Rule'),
        ),
    ]
