# Generated by Django 4.2.7 on 2024-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskaudit',
            options={'verbose_name': 'Task Audit', 'verbose_name_plural': 'Task Audit'},
        ),
    ]
