# Generated by Django 4.2.7 on 2024-02-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedauditlog',
            name='audit_sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
