# Generated by Django 4.2.7 on 2024-05-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_tools_stats', '0021_auto_20230210_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDashboardStats',
            fields=[
                ('dashboardstats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_tools_stats.dashboardstats')),
            ],
            bases=('admin_tools_stats.dashboardstats',),
        ),
    ]
