# Generated by Django 4.2.7 on 2024-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdashboardstats',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboard'},
        ),
    ]
