# Generated by Django 4.2.7 on 2024-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refenrencetype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refvalues',
            name='ref_value_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Ref_Value_id'),
        ),
    ]
