# Generated by Django 4.2.7 on 2024-02-13 17:49

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOT_Type',
            fields=[
                ('iot_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'IOT_Types',
            },
        ),
        migrations.CreateModel(
            name='IOT_Device',
            fields=[
                ('iot_device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('serialnumber', models.CharField(max_length=40)),
                ('externalid', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=40, max_length=40, prefix='', unique=True)),
                ('iot_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.iot_type')),
            ],
            options={
                'verbose_name_plural': 'IOT_Devices',
            },
        ),
    ]
