# Generated by Django 4.2.7 on 2024-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_iot_device_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device',
            name='iot_device_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='IOT_Device_Id'),
        ),
        migrations.AlterField(
            model_name='iot_type',
            name='iot_type_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='IOT_Type_Id'),
        ),
    ]
