# Generated by Django 4.2.7 on 2024-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_iot_device_created_by_iot_device_created_dt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iot_device',
            options={'verbose_name': 'Registered IoT Device', 'verbose_name_plural': 'Registered IoT Devices'},
        ),
    ]
