# Generated by Django 4.2.7 on 2024-02-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_iot_device_iot_device_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iot_device',
            options={'verbose_name': 'IOT Device', 'verbose_name_plural': 'IOT Devices'},
        ),
        migrations.AlterModelOptions(
            name='iot_type',
            options={'verbose_name': 'IOT Type', 'verbose_name_plural': 'IOT Types'},
        ),
    ]
